{
 "title": "VMAX Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "StorageGroup",
    "label": "Storage Group",
    "query": "SHOW TAG VALUES WITH KEY = \"Storage Group\""
   },
   {
    "name": "Host",
    "label": "Host",
    "query": "SHOW TAG VALUES WITH KEY = \"Host\""
   },
   {
    "name": "PortGroup",
    "label": "Port Group",
    "query": "SHOW TAG VALUES WITH KEY = \"Port Group\""
   },
   {
    "name": "DirectorType",
    "label": "Director Type",
    "query": "SHOW TAG VALUES WITH KEY = \"Director Type\""
   },
   {
    "name": "Array",
    "label": "Array SN",
    "query": "SHOW TAG VALUES WITH KEY = \"S/N\""
   },
   {
    "name": "Location",
    "label": "Location",
    "query": "SHOW TAG VALUES WITH KEY = \"Location\""
   }
  ]
 },
 "panels": [
  {
   "title": "Write Response Time",
   "type": "singlestat",
   "description": "Current max between all selected arrays.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "Array Write Response Time",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Array",
     "select": [
      [
       { "params": [ "WriteResponseTime" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Location", "operator": "=~", "value": "/^$Location$/" },
      { "condition": "AND", "key": "S/N", "operator": "=~", "value": "/^$Array$/" }
     ]
    }
   ]
  },
  {
   "title": "Read Response Time",
   "type": "singlestat",
   "description": "Current max between all selected arrays.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "Array Write Response Time",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Array",
     "select": [
      [
       { "params": [ "ReadResponseTime" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Location", "operator": "=~", "value": "/^$Location$/" },
      { "condition": "AND", "key": "S/N", "operator": "=~", "value": "/^$Array$/" }
     ]
    }
   ]
  },
  {
   "title": "Critical Alerts",
   "type": "singlestat",
   "description": "Total across all selected arrays, FATAL + CRITICAL alerts.",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Alerts",
     "select": [
      [
       { "params": [ "alerts_fatal_critical" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "S/N", "operator": "=~", "value": "/^$Array$/" },
      { "condition": "AND", "key": "Location", "operator": "=~", "value": "/^$Location$/" }
     ]
    }
   ]
  },
  {
   "title": "Warning Alerts",
   "type": "singlestat",
   "description": "Total across all selected arrays, MINOR + WARNING alerts.",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Alerts",
     "select": [
      [
       { "params": [ "alerts_minor_warning" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Location", "operator": "=~", "value": "/^$Location$/" },
      { "condition": "AND", "key": "S/N", "operator": "=~", "value": "/^$Array$/" }
     ]
    }
   ]
  },
  {
   "title": "Info Alerts",
   "type": "singlestat",
   "description": "Total across all selected arrays, INFORMATION alerts.",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Alerts",
     "select": [
      [
       { "params": [ "alerts_information" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Location", "operator": "=~", "value": "/^$Location$/" },
      { "condition": "AND", "key": "S/N", "operator": "=~", "value": "/^$Array$/" }
     ]
    }
   ]
  },
  {
   "title": "% Free (Cap)",
   "type": "singlestat",
   "description": "Minimum between all selected arrays.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SRP",
     "select": [
      [
       { "params": [ "array_free_percent" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "* 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "Location", "operator": "=~", "value": "/^$Location$/" },
      { "condition": "AND", "key": "S/N", "operator": "=~", "value": "/^$Array$/" }
     ]
    }
   ]
  },
  {
   "title": "Free (GB)",
   "type": "singlestat",
   "description": "Minimum between all selected arrays.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SRP",
     "select": [
      [
       { "params": [ "array_free_capacity" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "Location", "operator": "=~", "value": "/^$Location$/" },
      { "condition": "AND", "key": "S/N", "operator": "=~", "value": "/^$Array$/" }
     ]
    }
   ]
  },
  {
   "title": "Thin Ratio",
   "type": "singlestat",
   "description": "Average across all selected arrays.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Array",
     "select": [
      [
       { "params": [ "VPEfficiencyRatio" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Location", "operator": "=~", "value": "/^$Location$/" },
      { "condition": "AND", "key": "S/N", "operator": "=~", "value": "/^$Array$/" }
     ]
    }
   ]
  },
  {
   "title": "Compression Ratio",
   "type": "singlestat",
   "description": "Average across all selected arrays.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current"
  },
  { "title": "Array Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Array IOPs",
   "type": "graph",
   "description": "Sum across all selected arrays.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "FE Read IOPs",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Array",
     "select": [
      [
       { "params": [ "HostReads" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "S/N", "operator": "=~", "value": "/^$Array$/" },
      { "condition": "AND", "key": "Location", "operator": "=~", "value": "/^$Location$/" }
     ]
    },
    {
     "alias": "FE Write IOPs",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Array",
     "select": [
      [
       { "params": [ "HostWrites" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "S/N", "operator": "=~", "value": "/^$Array$/" },
      { "condition": "AND", "key": "Location", "operator": "=~", "value": "/^$Location$/" }
     ]
    }
   ]
  },
  {
   "title": "Array MB/s",
   "type": "graph",
   "description": "Sum across all selected arrays.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "FE Read MB/s",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Array",
     "select": [
      [
       { "params": [ "HostMBReads" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Location", "operator": "=~", "value": "/^$Location$/" },
      { "condition": "AND", "key": "S/N", "operator": "=~", "value": "/^$Array$/" }
     ]
    },
    {
     "alias": "FE Write MB/s",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Array",
     "select": [
      [
       { "params": [ "HostMBWritten" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Location", "operator": "=~", "value": "/^$Location$/" },
      { "condition": "AND", "key": "S/N", "operator": "=~", "value": "/^$Array$/" }
     ]
    }
   ]
  },
  {
   "title": "Array Response Times",
   "type": "graph",
   "description": "Avg across all selected arrays.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Read Response Time",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Array",
     "select": [
      [
       { "params": [ "ReadResponseTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Location", "operator": "=~", "value": "/^$Location$/" },
      { "condition": "AND", "key": "S/N", "operator": "=~", "value": "/^$Array$/" }
     ]
    },
    {
     "alias": "Write Response Time",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Array",
     "select": [
      [
       { "params": [ "WriteResponseTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Location", "operator": "=~", "value": "/^$Location$/" },
      { "condition": "AND", "key": "S/N", "operator": "=~", "value": "/^$Array$/" }
     ]
    }
   ]
  },
  {
   "title": "Array % Cache Hit, % Reads",
   "type": "graph",
   "description": "Avg across all selected arrays.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "% Cache Hit",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Array",
     "select": [
      [
       { "params": [ "PercentHit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Location", "operator": "=~", "value": "/^$Location$/" },
      { "condition": "AND", "key": "S/N", "operator": "=~", "value": "/^$Array$/" }
     ]
    },
    {
     "alias": "% Reads",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Array",
     "select": [
      [
       { "params": [ "PercentReads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Location", "operator": "=~", "value": "/^$Location$/" },
      { "condition": "AND", "key": "S/N", "operator": "=~", "value": "/^$Array$/" }
     ]
    }
   ]
  },
  { "title": "Storage Group Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Storage Group IOPs",
   "type": "graph",
   "description": "Sum across all selected Storage Groups.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "SG Read IOPs",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Storage Group",
     "select": [
      [
       { "params": [ "HostReads" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Storage Group", "operator": "=~", "value": "/^$StorageGroup$/" }
     ]
    },
    {
     "alias": "SG Write IOPs",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Storage Group",
     "select": [
      [
       { "params": [ "HostWrites" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Storage Group", "operator": "=~", "value": "/^$StorageGroup$/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Group MB/s",
   "type": "graph",
   "description": "Sum across all selected Storage Groups.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "SG Read MB/s",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Storage Group",
     "select": [
      [
       { "params": [ "HostMBReads" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Storage Group", "operator": "=~", "value": "/^$StorageGroup$/" }
     ]
    },
    {
     "alias": "SG Write MB/s",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Storage Group",
     "select": [
      [
       { "params": [ "HostMBWritten" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Storage Group", "operator": "=~", "value": "/^$StorageGroup$/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Group Response Times",
   "type": "graph",
   "description": "Maximum between all selected Storage Groups.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "SG Read Response Time",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Storage Group",
     "select": [
      [
       { "params": [ "ReadResponseTime" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Storage Group", "operator": "=~", "value": "/^$StorageGroup$/" }
     ]
    },
    {
     "alias": "SG Write Response Time",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Storage Group",
     "select": [
      [
       { "params": [ "WriteResponseTime" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Storage Group", "operator": "=~", "value": "/^$StorageGroup$/" }
     ]
    }
   ]
  },
  {
   "title": "Single Storage Group Metrics",
   "type": "graph",
   "description": "May not be representative if multiple Storage Groups are selected especially if a SG has zero I/O. Average across all selected Storage Groups.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "% Random I/O",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Storage Group",
     "select": [
      [
       { "params": [ "PercentRandomIO" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Storage Group", "operator": "=~", "value": "/^$StorageGroup$/" }
     ]
    },
    {
     "alias": "% Cache Hit",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Storage Group",
     "select": [
      [
       { "params": [ "PercentHit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Storage Group", "operator": "=~", "value": "/^$StorageGroup$/" }
     ]
    },
    {
     "alias": "Average I/O Size",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Storage Group",
     "select": [
      [
       { "params": [ "AvgIOSize" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Storage Group", "operator": "=~", "value": "/^$StorageGroup$/" }
     ]
    }
   ]
  },
  { "title": "Host Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Host IOPs",
   "type": "graph",
   "description": "Sum across all selected Hosts.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Host Read IOPs",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Host",
     "select": [
      [
       { "params": [ "Reads" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "Host Write IOPs",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Host",
     "select": [
      [
       { "params": [ "Writes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Host MB/s",
   "type": "graph",
   "description": "Sum across all selected Hosts.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Host Read MB/s",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Host",
     "select": [
      [
       { "params": [ "HostMBReads" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "Host Write MB/s",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Host",
     "select": [
      [
       { "params": [ "HostMBWrites" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Host Response Times",
   "type": "graph",
   "description": "Maximum between all selected Hosts.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Host Read Response Time",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Host",
     "select": [
      [
       { "params": [ "ReadResponseTime" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "Host Write Response Time",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Host",
     "select": [
      [
       { "params": [ "WriteResponseTime" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  { "title": "Director & Port Group Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Director % Busy",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Director % Busy",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Director",
     "select": [
      [
       { "params": [ "PercentBusy" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Director Type", "operator": "=~", "value": "/^$DirectorType$/" }
     ]
    }
   ]
  },
  {
   "title": "Port Group Avg I/O Size (kB)",
   "type": "graph",
   "description": "Average across all selected Port Groups.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "PG Avg IO Size (kB)",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Port Group",
     "select": [
      [
       { "params": [ "AvgIOSize" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Port Group", "operator": "=~", "value": "/^$PortGroup$/" }
     ]
    }
   ]
  },
  { "title": "Capacity Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Array Capacity (TB)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Usable Capacity (TB)",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SRP",
     "select": [
      [
       { "params": [ "total_usable_cap_gb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Subscribed Capacity (TB)",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SRP",
     "select": [
      [
       { "params": [ "total_subscribed_cap_gb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Allocated Capacity (TB)",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SRP",
     "select": [
      [
       { "params": [ "total_allocated_cap_gb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  }
 ]
}